Write to merge into test-green-head
Needs to run out of true-head to run on a true-head push, but the PR to review will be for changing it to merge into the actual green-head. Also, fetch unshallow to resolve unrelated histories merge, and set identity to Berwin.

diff --git a/.github/workflows/green-head-merge.yml b/.github/workflows/green-head-merge.yml
--- a/.github/workflows/green-head-merge.yml
+++ b/.github/workflows/green-head-merge.yml
@@ -17,11 +17,14 @@ jobs:
         run: sudo apt install python3 && pip install pytest
 
       - name: true-head branch checkout
-        run: git fetch --all && git checkout true-head
+        run: git fetch --all --unshallow && git checkout true-head
 
       - name: Run end-to-end test on true head
         working-directory: ./testing/end_to_end_tests
-        run: pytest *.py # returns 0 exit code if all tests pass
+        run: pytest # returns 0 exit code if all tests pass
+
+      - name: Set identity to Berwin
+        run: git config --global user.email "blan@olin.edu" && git config --global user.name "Berwin Lan"
 
       - name: Merge into main if tests pass
-        run: if [[ $? -eq 0 ]]; then git checkout green-head && git pull && git merge true-head && git push; fi
+        run: if [[ $? -eq 0 ]]; then git checkout test-green-head && git pull && git merge true-head && git push; fi
